In [1]:
import numpy as np

In [2]:
corpus = ["this pasta is very tasty and affordable",
          "this pasta is not tasty and is affordable",
          "this pasta is delicious and cheap",
         "pasta is tasty and pasta tastes good"]


In [3]:
def create_dict(corpus):
    unique_words = set()
    for row in corpus:
        for word in row.split(" "):
            unique_words.add(word)
    unique_words = sorted(list(unique_words))
    vocab = {i:j for i,j in enumerate(unique_words)}
    return vocab
    
vocab = create_dict(corpus)
print(vocab)

{0: 'affordable', 1: 'and', 2: 'cheap', 3: 'delicious', 4: 'good', 5: 'is', 6: 'not', 7: 'pasta', 8: 'tastes', 9: 'tasty', 10: 'this', 11: 'very'}


In [4]:
def doc_to_list(corpus):
    corpus_list=[]
    for row in corpus:
        temp = []
        for word in row.split(" "):
            temp.append(word)
        corpus_list.append(temp)
    return corpus_list
corpus_list = doc_to_list(corpus)
print(corpus_list)

[['this', 'pasta', 'is', 'very', 'tasty', 'and', 'affordable'], ['this', 'pasta', 'is', 'not', 'tasty', 'and', 'is', 'affordable'], ['this', 'pasta', 'is', 'delicious', 'and', 'cheap'], ['pasta', 'is', 'tasty', 'and', 'pasta', 'tastes', 'good']]


In [5]:
def bow(corpus_list,vocab):
    bow=[]
    for row in corpus_list:
        temp=[0]*len(vocab)
        for word in row:
            for n in vocab:
                if vocab[n] == word:
                    temp[n]+=1
        bow.append(temp)
    return bow
bow =  bow(corpus_list,vocab)
print(bow)
    

[[1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1], [1, 1, 0, 0, 0, 2, 1, 1, 0, 1, 1, 0], [0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0], [0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 0]]


In [6]:
def binary_bow(corpus_list,vocab):
    corpus_binary_bow = []
    for row in corpus_list:
        temp = [0]*len(vocab)
        for n in range(len(vocab)):
            if vocab[n] in row:
                temp[n] += 1
        corpus_binary_bow.append(temp)
    return corpus_binary_bow
binary_bow = binary_bow(corpus_list,vocab)
print(binary_bow) 

[[1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1], [1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0], [0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0], [0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0]]


In [7]:
def calc_dist(v1,v2):
    temp=[]
    for i in range(len(v1)):
        if v1[i]==v2[i]:
            continue
        else:
            temp.append(float((v1[i]-v2[i])**2))
    dist = np.sqrt(sum(temp))
    return dist

dist = calc_dist(bow[0],bow[1])
print(dist)

1.7320508075688772


In [8]:
bow_dist = np.zeros(shape=(4,4), dtype=float)

for i in range(len(bow_dist)):
    for j in range(len(bow_dist[i])):
        bow_dist[i][j] = calc_dist(bow[i],bow[j])
print(bow_dist)

[[0.         1.73205081 2.23606798 2.44948974]
 [1.73205081 0.         2.44948974 2.64575131]
 [2.23606798 2.44948974 0.         2.64575131]
 [2.44948974 2.64575131 2.64575131 0.        ]]
